/*
  Production payment hook.
  Keep mode as "demo" for the interactive prototype.
  For a real launch, use a secure hosted checkout URL generated by Stripe,
  Razorpay or another payment provider. Never place secret API keys here.
*/
window.INSIGHTGUARD_PAYMENT_CONFIG = {
  mode: "demo",
  provider: "hosted-checkout",
  hostedCheckoutUrl: ""
};

